name: BUILD

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URI: ${{secrets.DATABASE_URI}}
      TEST_DATABASE_URI: ${{secrets.TEST_DATABASE_URI}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Setup Python
        uses: actions/setup-python@v2  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pylint
        run: |
          python lint.py --path ./app.py --threshold 5
      
      - name: Run tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build 
        run: |
          docker build -f Dockerfile -t vijaysaran07/flask-crud-api:${{ github.sha }} -t vijaysaran07/flask-crud-api:latest .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vijaysaran07/flask-crud-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
      
      - name: Docker Push
        run: |
          docker push vijaysaran07/flask-crud-api

